service: apollo-lambda
provider:
  name: aws
  runtime: nodejs12.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    # this sets up API Gateway events for us.
    # https://www.serverless.com/framework/docs/providers/aws/events/apigateway/#simple-http-endpoint
    events:
      - http:
          path: graphql
          method: post
          # CORS allows sharing of resources from any origin
          # (typically requests from the browser must come from the same
          # domain, i.e walmart.com cannot load data from amazon.com
          # unless amazon.com allows it with CORS)
          cors: true
      - http:
          path: graphql
          method: get
          cors: true